# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocolBufferReducer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bprotocolBufferReducer.proto\x12\tMapReduce\"=\n\x0cReducerInput\x12\x15\n\rfileInputList\x18\x01 \x03(\t\x12\x16\n\x0eoutputFileName\x18\x02 \x01(\t\"0\n\rReducerOutput\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\\\n\x07Reducer\x12Q\n\x1cGetInputForReducerOperations\x12\x17.MapReduce.ReducerInput\x1a\x18.MapReduce.ReducerOutputb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocolBufferReducer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REDUCERINPUT._serialized_start=42
  _REDUCERINPUT._serialized_end=103
  _REDUCEROUTPUT._serialized_start=105
  _REDUCEROUTPUT._serialized_end=153
  _REDUCER._serialized_start=155
  _REDUCER._serialized_end=247
# @@protoc_insertion_point(module_scope)
