# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocolBufferMaster.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aprotocolBufferMaster.proto\x12\tMapReduce\"*\n\x11IntermediateInput\x12\x15\n\rfileInputList\x18\x01 \x03(\t\"5\n\x12IntermediateOutput\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2_\n\x06Master\x12U\n\x16GetIntermediateResults\x12\x1c.MapReduce.IntermediateInput\x1a\x1d.MapReduce.IntermediateOutputb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocolBufferMaster_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INTERMEDIATEINPUT._serialized_start=41
  _INTERMEDIATEINPUT._serialized_end=83
  _INTERMEDIATEOUTPUT._serialized_start=85
  _INTERMEDIATEOUTPUT._serialized_end=138
  _MASTER._serialized_start=140
  _MASTER._serialized_end=235
# @@protoc_insertion_point(module_scope)
