# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import protocolBufferMaster_pb2 as protocolBufferMaster__pb2


class MasterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetIntermediateResults = channel.unary_unary(
                '/MapReduce.Master/GetIntermediateResults',
                request_serializer=protocolBufferMaster__pb2.IntermediateInput.SerializeToString,
                response_deserializer=protocolBufferMaster__pb2.IntermediateOutput.FromString,
                )


class MasterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetIntermediateResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MasterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetIntermediateResults': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIntermediateResults,
                    request_deserializer=protocolBufferMaster__pb2.IntermediateInput.FromString,
                    response_serializer=protocolBufferMaster__pb2.IntermediateOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MapReduce.Master', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Master(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetIntermediateResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MapReduce.Master/GetIntermediateResults',
            protocolBufferMaster__pb2.IntermediateInput.SerializeToString,
            protocolBufferMaster__pb2.IntermediateOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
