# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocolBufferMapper.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aprotocolBufferMapper.proto\x12\tMapReduce\":\n\x0bMapperInput\x12\x15\n\rfileInputList\x18\x01 \x03(\t\x12\x14\n\x0creducerCount\x18\x02 \x01(\x04\"/\n\x0cMapperOutput\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2X\n\x06Mapper\x12N\n\x1bGetInputForMapperOperations\x12\x16.MapReduce.MapperInput\x1a\x17.MapReduce.MapperOutputb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocolBufferMapper_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MAPPERINPUT._serialized_start=41
  _MAPPERINPUT._serialized_end=99
  _MAPPEROUTPUT._serialized_start=101
  _MAPPEROUTPUT._serialized_end=148
  _MAPPER._serialized_start=150
  _MAPPER._serialized_end=238
# @@protoc_insertion_point(module_scope)
