# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import protocolBufferMapper_pb2 as protocolBufferMapper__pb2


class MapperStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInputForMapperOperations = channel.unary_unary(
                '/MapReduce.Mapper/GetInputForMapperOperations',
                request_serializer=protocolBufferMapper__pb2.MapperInput.SerializeToString,
                response_deserializer=protocolBufferMapper__pb2.MapperOutput.FromString,
                )


class MapperServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetInputForMapperOperations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MapperServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInputForMapperOperations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInputForMapperOperations,
                    request_deserializer=protocolBufferMapper__pb2.MapperInput.FromString,
                    response_serializer=protocolBufferMapper__pb2.MapperOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MapReduce.Mapper', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Mapper(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetInputForMapperOperations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MapReduce.Mapper/GetInputForMapperOperations',
            protocolBufferMapper__pb2.MapperInput.SerializeToString,
            protocolBufferMapper__pb2.MapperOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
