# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import protocolBufferReducer_pb2 as protocolBufferReducer__pb2


class ReducerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInputForReducerOperations = channel.unary_unary(
                '/MapReduce.Reducer/GetInputForReducerOperations',
                request_serializer=protocolBufferReducer__pb2.ReducerInput.SerializeToString,
                response_deserializer=protocolBufferReducer__pb2.ReducerOutput.FromString,
                )


class ReducerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetInputForReducerOperations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReducerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInputForReducerOperations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInputForReducerOperations,
                    request_deserializer=protocolBufferReducer__pb2.ReducerInput.FromString,
                    response_serializer=protocolBufferReducer__pb2.ReducerOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MapReduce.Reducer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Reducer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetInputForReducerOperations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MapReduce.Reducer/GetInputForReducerOperations',
            protocolBufferReducer__pb2.ReducerInput.SerializeToString,
            protocolBufferReducer__pb2.ReducerOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
